// for ingredient details
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INGREDIENTS_FETCH_FAILED = 'INGREDIENTS_FETCH_FAILED';

// for order details
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';
export const PURCHASE_INIT = "PURCHASE_INIT";

export const USER_SIGN_IN_START = "USER_SIGN_IN_START";
export const USER_SIGN_UP_START = "USER_SIGN_UP_START";
export const USER_SIGN_UP_SUCCESS = "USER_SIGN_UP_SUCCESS";
export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";
export const USER_SIGN_IN_FAILED = "USER_SIGN_IN_FAILED";
export const USER_SIGN_UP_FAILED = "USER_SIGN_UP_FAILED";

export const USER_LOGOUT = "USER_LOGOUT";


